### PR TITLE
added price compare extension idea

### PR DESCRIPTION
**Pull request by sauravraw**
Added BrowserExtension idea 
where the user can add the product URL and compare the price where he is getting the low price and high price.

### CODE REVIEW

**Review by sauravraw — COMMENTED** [review]
Thanks for the update

**Comment by KapilKumar7** [comment]
Thanks for your valuable contribution 😊.

**Comment by sauravraw** [comment]
Hi Please add Hacktoberfest - accepted label
thanks in advance :)

**Comment by KapilKumar7** [comment]
> Hi Please add Hacktoberfest - accepted label thanks in advance :)
> 
> Screenshot 2022-10-18 at 9 53 59 PM

Sorry for the inconvenience Saurav, I have added the label already, But let me check again where is the problem.

**Pull request merged**
